---
- name: Install Jenkins on EC2
  hosts: jenkins
  become: yes

  tasks:
    - name: Install Java (OpenJDK)
      dnf:
        name: java-17-amazon-corretto
        state: present

    - name: Add Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      dnf:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: true
